### ISSUE TITLE
Corriger le dernier TP

### ISSUE THREAD

**Issue by laurentlp** [Ressius/DiviMaxAPI#2]
# **Correction du dernier TP**

- [x]  Try-catch sur les calls de BD
- [x]  Valider toutes les vues
- [x]  Valider que l'inscription d'un admin est possible

* Ajouter les tâches manquantes

**Comment by Ressius** [comment]
Re-vérifier les try-catch a la fin du TP actuel, pour englober les intéractions avec l'API
